### ISSUE TITLE
Playoff Games: List Index Out of Range

### ISSUE THREAD

**Issue by spoonertaylor** [mcbarlowe/nba_scraper#1]
I have been trying to get the play by play for playoff games and running into the following error:

```
nba_df = ns.scrape_game([41700151])
Scraping game id: 0041700151
Traceback (most recent call last):

  File "<ipython-input-28-ffa52b1d949b>", line 1, in <module>
    nba_df = ns.scrape_game([41700151])

  File "/anaconda3/lib/python3.7/site-packages/nba_scraper/nba_scraper.py", line 33, in scrape_game
    scraped_games.append(sf.scrape_pbp(f"00{game}"))

  File "/anaconda3/lib/python3.7/site-packages/nba_scraper/scrape_functions.py", line 635, in scrape_pbp
    clean_df = get_lineups(clean_df)

  File "/anaconda3/lib/python3.7/site-packages/nba_scraper/scrape_functions.py", line 211, in get_lineups
    away_ids_names = [(x, dataframe[dataframe['player1_id'] == x]['player1_name'].unique()[0]) for x in away_lineups[0]]

IndexError: list index out of range
```

From some very initial checking, it looks like regular season game game id's start with a 2 while playoff games start with a 4 in the game id.

**Comment by mcbarlowe** [comment]
Yeah the lineups API takes a regular season/playoffs keyword I didn't notice hoping to have an update and new release pushed by tonight/tomorrow at the latest

**Comment by mcbarlowe** [comment]
Bug fixed in [v_02.4](https://github.com/mcbarlowe/nba_scraper/releases/tag/v_02.4) and available to upgrade on PyPi
