### ISSUE TITLE
'HOME' KeyError on Windows

### ISSUE THREAD

**Issue by dcstats** [mcbarlowe/nba_scraper#11]
in running the scraper on Windows Command Prompt, I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\nba_scraper\nba_scraper.py", line 40, in <module>
    def scrape_date_range(date_from, date_to, data_format='pandas', data_dir=f"{os.environ['HOME']}/nbadata.csv"):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

Windows doesn't have the HOME environment variable; it uses USERPROFILE instead.

**Comment by dcstats** [comment]
scrape_date_range was fixed, but same error in functions scrape_game and scrape_season:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\nba_scraper\nba_scraper.py", line 76, in <module>
    def scrape_game(game_ids, data_format='pandas', data_dir=f"{os.environ['HOME']}/nbadata.csv"):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by mcbarlowe** [comment]
Closing issue was fixed with commit 7e9ccd65c40ef970bdb94a52c863398dd2aeeab4
