### ISSUE TITLE
Error scraping game 21800053

### ISSUE THREAD

**Issue by mcbarlowe** [mcbarlowe/nba_scraper#7]
Looks like for some reason a players not found in the dataframe or the lineups are returning an empty list this needs to be looked at.

```
>>> test = ns.scrape_game([21800053])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbarlowe/code/python/nba_scraper/nba_scraper/nba_scraper.py", line 98, in scrape_game
    scraped_games.append(sf.main_scrape(f"00{game}"))
  File "/Users/mbarlowe/code/python/nba_scraper/nba_scraper/scrape_functions.py", line 1138, in main_scrape
    game_df))
  File "/Users/mbarlowe/code/python/nba_scraper/nba_scraper/scrape_functions.py", line 959, in get_lineup
    ['player1_name'].unique()[0]) for x in away_lineups[0]]
  File "/Users/mbarlowe/code/python/nba_scraper/nba_scraper/scrape_functions.py", line 959, in <listcomp>
    ['player1_name'].unique()[0]) for x in away_lineups[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by mcbarlowe** [comment]
Fixed with commit 9914f8fcb5fd5a295c6b2c84eb98d9ee0e36d7c4
